Add working blacklist, print socket with status, and save to json
Syncano/sockets pull request #1
Opened 2016-12-02 13:12 UTC by tomsonpl

![screen shot 2016-12-02 at 14 12 20](https://cloud.githubusercontent.com/assets/16632552/20835162/5cbc91c0-b899-11e6-9399-7bb4aef4f0c6.png)
![screen shot 2016-12-02 at 14 12 12](https://cloud.githubusercontent.com/assets/16632552/20835161/5cbc3338-b899-11e6-93e0-f9e2607d511c.png)

2016-12-02 13:26 UTC, patrykkopycinski requested changes

2016-12-02 13:26 UTC, patrykkopycinski commented on _node-machine_to_Syncano-script/test.js
> +  function whiteListMachine(machine, blackList) {
`function whiteListMachine(machine, blackList = BLACK_LIST) {`

2016-12-02 13:26 UTC, patrykkopycinski commented on _node-machine_to_Syncano-script/test.js
> +    .filter((machine) => whiteListMachine(machine, BLACK_LIST))
`.filter(whiteListMachine)`

2016-12-02 13:26 UTC, patrykkopycinski commented on _node-machine_to_Syncano-script/test.js
> +      const install_url = `https://raw.githubusercontent.com/Syncano/sockets/master/${variableName}/${version}/socket.yaml`;
it should try to install socket from local files, because we want to tests sockets before we push them to the registry

2016-12-02 13:26 UTC, patrykkopycinski commented on _node-machine_to_Syncano-script/test.js
> +  const installSocket = (name, install_url) => {
what is the purpose of having a method that the only thing it does is a call another method?

2016-12-02 13:26 UTC, patrykkopycinski commented on _node-machine_to_Syncano-script/test.js
> +        'https://api.syncano.io/v2/instances/INSTANCE_NAME/sockets/install/',
it should be possible to set different different host

2016-12-02 13:26 UTC, patrykkopycinski commented on _node-machine_to_Syncano-script/test.js
> +          payload: {}
is it necessary?

2016-12-02 13:26 UTC, patrykkopycinski commented on _node-machine_to_Syncano-script/test.js
> +      .then((response) => {
`.then(console.log)`

2016-12-02 13:26 UTC, patrykkopycinski commented on _node-machine_to_Syncano-script/test.js
> +const setCallsArray = () => {
it should be just a `function` instead of `const`

2016-12-02 13:26 UTC, patrykkopycinski commented on _node-machine_to_Syncano-script/test.js
> +    if (blackList.indexOf(machine.identity) > -1) {
`return blackList.indexOf(machine.identity) !== -1`

2016-12-02 13:26 UTC, patrykkopycinski commented on _node-machine_to_Syncano-script/test_list.js
> +const listSockets = function() {
`function listSockets`

2016-12-02 13:26 UTC, patrykkopycinski commented on _node-machine_to_Syncano-script/test_list.js
> +      const path = './valid_sockets.json';
require should be done at the top of the file

2016-12-02 13:26 UTC, patrykkopycinski commented on _node-machine_to_Syncano-script/test_list.js
> +      }
`console.log(e)`

2016-12-02 13:26 UTC, patrykkopycinski commented on _node-machine_to_Syncano-script/test_list.js
> +      response.data.objects.forEach(function(item) {
what this callback does?

2016-12-02 13:26 UTC, patrykkopycinski commented on _node-machine_to_Syncano-script/test_list.js
> +    .catch(function(error) {
`.catch(console.log)`

2016-12-02 13:26 UTC, patrykkopycinski commented on _node-machine_to_Syncano-script/test_list.js
> +
unnecessary empty lines

2016-12-02 13:36 UTC, tomsonpl commented on _node-machine_to_Syncano-script/test.js
> +  const installSocket = (name, install_url) => {
there were 2 functions inside, I refactored it, and forgot to delete the outer function. thanks

2016-12-02 13:45 UTC, tomsonpl commented on _node-machine_to_Syncano-script/test.js
> +    if (blackList.indexOf(machine.identity) > -1) {
I think this brings the opposite result, can you double check please?

2016-12-02 17:39 UTC, tomsonpl commented on _node-machine_to_Syncano-script/connection.js
> +import Syncano from 'syncano';
I dont use this (connection.js) file, will delete it with the next commit.

2016-12-02 17:44 UTC, patrykkopycinski requested changes

2016-12-02 17:44 UTC, patrykkopycinski commented on _node-machine_to_Syncano-script/connection.js
> +import globals from '../../e2e/globals';
where is this file?

2016-12-02 17:44 UTC, patrykkopycinski commented on _node-machine_to_Syncano-script/connection.js
> +
unnecessary empty line

2016-12-02 17:44 UTC, patrykkopycinski commented on _node-machine_to_Syncano-script/test_list.js
> +const validSockets = './valid_sockets.json';
`validSocketsFile`

2016-12-02 17:44 UTC, patrykkopycinski commented on _node-machine_to_Syncano-script/test.js
> +    const rawAddress = 'https://raw.githubusercontent.com/Syncano/sockets/master'
it should be kept in helpers

2016-12-02 17:44 UTC, patrykkopycinski commented on _node-machine_to_Syncano-script/test.js
> +    .then(console.log)
do we want to always log all responses?

2016-12-02 17:44 UTC, patrykkopycinski commented on _node-machine_to_Syncano-script/script.js
> +const dedent = require('dedent');
is it in use?

2016-12-02 17:44 UTC, patrykkopycinski commented on _node-machine_to_Syncano-script/script.js
> +const mkdirp = require('mkdirp');
is it in use?

2016-12-02 17:44 UTC, patrykkopycinski commented on _node-machine_to_Syncano-script/script.js
> +const yaml = require('write-yaml');
is it in use?

2016-12-02 17:44 UTC, patrykkopycinski commented on _node-machine_to_Syncano-script/script.js
>  const machines = require('./data.json');
change name o file `data.json` => `machines.json`

2016-12-02 17:44 UTC, patrykkopycinski commented on _node-machine_to_Syncano-script/helpers.js
> +const host = 'api.syncano.rocks';
host should be taken from env variables, default : `api.syncano.io`

2016-12-02 17:44 UTC, patrykkopycinski commented on _node-machine_to_Syncano-script/helpers.js
> +let newAccountInfo = require('./newAccountInfo');
`let` => `const`

2016-12-02 17:44 UTC, patrykkopycinski commented on _node-machine_to_Syncano-script/generateCiCredentials.js
> +const generateCiCredentials = () => {
`function generateCiCredentials() {`

2016-12-02 17:44 UTC, patrykkopycinski commented on _node-machine_to_Syncano-script/generateCiCredentials.js
> +  const ciBaseEmail = process.env.CI_BASE_EMAIL;
Add all necessary env variable to the readme, and also set it by default to `syncano.bot@`

2016-12-02 17:44 UTC, patrykkopycinski commented on _node-machine_to_Syncano-script/createAccount.js
> +module.exports = account;
is it necessary?

2016-12-02 17:44 UTC, patrykkopycinski commented on _node-machine_to_Syncano-script/createAccount.js
> +let api_key;
is it in use?

2016-12-02 17:44 UTC, patrykkopycinski commented on _node-machine_to_Syncano-script/createAccount.js
> +let instance_name;
is it in use?

2016-12-02 17:44 UTC, patrykkopycinski commented on _node-machine_to_Syncano-script/createAccount.js
> +    connection = Syncano({accountKey: account.account_key, baseUrl: 'https://api.syncano.rocks'});
`'https://api.syncano.rocks'` it should be taken from helpers, and you shouldn't override connection, instead you should set `accountKey`

2016-12-02 17:44 UTC, patrykkopycinski commented on _node-machine_to_Syncano-script/connection.js
> +import Syncano from 'syncano';
is this file in use?

2016-12-02 17:45 UTC, tomsonpl commented on _node-machine_to_Syncano-script/connection.js
> +import Syncano from 'syncano';
no, leftover.

2016-12-02 17:48 UTC, tomsonpl commented on _node-machine_to_Syncano-script/script.js
> +const mkdirp = require('mkdirp');
yes

2016-12-02 17:48 UTC, tomsonpl commented on _node-machine_to_Syncano-script/script.js
> +const yaml = require('write-yaml');
yes

2016-12-05 10:34 UTC, tomsonpl commented on _node-machine_to_Syncano-script/createAccount.js
> +    connection = Syncano({accountKey: account.account_key, baseUrl: 'https://api.syncano.rocks'});
I don't really follow. Do you mean we should make const at the top, and delete the 15th line?

2016-12-06 14:45 UTC, gh3r requested changes
* Change script folder name to something more accurate
* Fix readme for correct instructions
* node script.js doesn't work `Error: Cannot find module './newAccountInfo'` Please corretly add steps how to run it
* Append scripts in package.json with command above, so user just needs to `npm run XXX` where XXX is how you gonna name the script
* Same for test commands

2016-12-14 16:33 UTC, tomsonpl commented
@gh3r @patrykkopycinski could you check the changes you requested? Then I will be able to branch it.

2016-12-14 16:39 UTC, merged