Add unit tests and es6 support to script
Syncano/sockets pull request #2
Opened 2016-12-15 12:07 UTC by tomsonpl

2016-12-16 01:38 UTC, Flixow commented on _socketsGenerator/test/test.test.js
> +      expect(result.withArgs(name).called).to.be.true;
What about: 
```
sinon.assert.called(result);
sinon.assert.calledWith(result, name);
```
On my mind you don't check now that method was called with argument if you wanted it.

2016-12-16 01:41 UTC, Flixow commented on _socketsGenerator/test.js
> +const getSocket = (name) => {
Function was worse?

2016-12-16 10:39 UTC, tomsonpl commented on _socketsGenerator/test.js
> +const getSocket = (name) => {
It wasn't, we just decided to make it with =>.

2016-12-16 15:39 UTC, patrykkopycinski requested changes

2016-12-16 15:39 UTC, patrykkopycinski commented on _socketsGenerator/createAccount.js
> +const createAccount = () => {
it was ok in previous version

2016-12-16 15:39 UTC, patrykkopycinski commented on _socketsGenerator/createAccount.js
> +          console.log('Account was created')
wrong indentation

2016-12-16 15:39 UTC, patrykkopycinski commented on _socketsGenerator/createAccount.js
> +if (process.argv[2] !== 'test/main_test.js') {
it'd be better to check if file with credentials exists instead of comparing args

2016-12-16 15:39 UTC, patrykkopycinski commented on _socketsGenerator/createSockets.js
> +const renderEndpoints = (endpoints) => {
`function renderEndpoints(endpoints) {`

2016-12-16 15:39 UTC, patrykkopycinski commented on _socketsGenerator/createSockets.js
> +const createDirs = (rootDir) => {
`function`

2016-12-16 15:39 UTC, patrykkopycinski commented on _socketsGenerator/createSockets.js
> +if (process.argv[2] !== 'test/main_test.js') {
the same as with `createAccount`

2016-12-16 15:39 UTC, patrykkopycinski commented on _socketsGenerator/package.json
> +    "babel-cli": "^6.18.0",
all dependencies should have strict version

2016-12-16 15:39 UTC, patrykkopycinski commented on _socketsGenerator/package.json
> +    "nodemon": "^1.11.0",
unused dependency

2016-12-16 15:39 UTC, patrykkopycinski commented on _socketsGenerator/test.js
> +const getSocket = (name) => {
`function`

2016-12-16 15:39 UTC, patrykkopycinski commented on _socketsGenerator/test.js
> +    return false;
instead of return false it'd better to let know why it didn't work

2016-12-16 15:39 UTC, patrykkopycinski commented on _socketsGenerator/test/createAccount.test.js
> +const { createAccount } = functions;
is it necessary?

2016-12-19 09:37 UTC, tomsonpl commented on _socketsGenerator/createAccount.js
> +if (process.argv[2] !== 'test/main_test.js') {
I used this in all 3 scripts, as long as it would work here, it won't in the others. Is there any other way to stop scripts to run on test?

2016-12-19 13:00 UTC, patrykkopycinski approved these changes

2016-12-19 13:00 UTC, merged

2016-12-20 16:16 UTC, gh3r commented on _socketsGenerator/test/test.test.js
> +      expect(whiteListMachine(name, blackList)).to.be.true;
does the same thing like test before

2016-12-20 16:17 UTC, gh3r commented on _socketsGenerator/test/test.test.js
> +      sinon.assert.calledWith(result, name);
why called and calledWith, calledWith does same thing like called but more.

2016-12-20 16:19 UTC, gh3r commented on _socketsGenerator/test/test.test.js
> +      expect(checkIfInstalled(name)).to.be.false;
why checking if false if tests suggests that response should be string.

2016-12-20 16:19 UTC, gh3r commented on _socketsGenerator/test/test.test.js
> +      expect(createZip(name, version)).to.be.false;
same, why false when checking if correct types

2016-12-20 16:21 UTC, gh3r commented on _socketsGenerator/test/test.test.js
> +      expect(deleteZip(name)).to.be.false;
💀

2016-12-20 16:24 UTC, gh3r commented on _socketsGenerator/test/createSockets.test.js
> +    beforeEach(function() {
be sure to check if beforeEach is nessesary, as it results in longer tests, try checking before settling for one result

2016-12-20 16:27 UTC, gh3r commented on _socketsGenerator/test/createAccount.test.js
> +  var result = sinon.stub(functions, 'createAccount').returns(apiResponse);
why this is not restored after finishing tests?!?

2016-12-20 16:28 UTC, gh3r commented on _socketsGenerator/test/createSockets.test.js
> +    var result = sinon.stub(functions, 'createDirs')
also here... do it in before/after or use sinono.test and clean your stubs!!!!

2016-12-20 16:29 UTC, gh3r reviewed
@_@